table 2-nowe_artykuly_monthly
	lineageTag: 98a57663-89ae-4bc3-81d8-c83d3da670ac

	column month
		dataType: dateTime
		formatString: General Date
		lineageTag: 32476cc3-fc89-4222-924d-63458d3a34f2
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column 'total.content'
		dataType: int64
		formatString: 0
		lineageTag: d6980dae-f155-40b8-a255-d72821715ded
		summarizeBy: sum
		sourceColumn: total.content

		annotation SummarizationSetBy = Automatic

	partition 2-nowe_artykuly_monthly = m
		mode: import
		source =
				let
				  Źródło = Csv.Document(File.Contents("D:\AnalizaDanych\000_projekty\BI_NGO_Wikipedia\BI_NGO_Wikipedia\data\2-nowe_artykuly_monthly.csv"), [Delimiter = ",", Columns = 2, QuoteStyle = QuoteStyle.None]),
				  #"Nagłówki o podwyższonym poziomie" = Table.PromoteHeaders(Źródło, [PromoteAllScalars = true]),
				  #"Zmieniono typ kolumny" = Table.TransformColumnTypes(#"Nagłówki o podwyższonym poziomie", {{"month", type datetime}, {"total.content", Int64.Type}}, "pl")
				in
				  #"Zmieniono typ kolumny"

