table 5-top_1000_artykulow_monthly
	lineageTag: b391ff41-e1a1-4dde-8bac-705cac912e3d

	column page_id
		dataType: int64
		formatString: 0
		lineageTag: 0a2c934c-9acf-4551-b825-e423cef5770d
		summarizeBy: sum
		sourceColumn: page_id

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 5ee964aa-84ca-4c3d-b011-55a620bd373a
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: cf18854d-eec6-4231-864b-e9c955c70ba6
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column rank
		dataType: int64
		formatString: 0
		lineageTag: 9e9b64d1-e391-43de-bc2d-0b387476e125
		summarizeBy: sum
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 850e6f05-6027-40c2-999b-5f40beaae172
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column views
		dataType: int64
		formatString: 0
		lineageTag: a64925a2-2e4c-4c18-9ed5-78cdbb90336a
		summarizeBy: sum
		sourceColumn: views

		annotation SummarizationSetBy = Automatic

	partition 5-top_1000_artykulow_monthly = m
		mode: import
		queryGroup: Zapytania
		source =
				let
				  Źródło = Csv.Document(File.Contents("D:\AnalizaDanych\000_projekty\BI_NGO_Wikipedia\BI_NGO_Wikipedia\data\5-top_1000_artykulow_monthly.csv"), [Delimiter = ",", Columns = 6, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Nagłówki o podwyższonym poziomie" = Table.PromoteHeaders(Źródło, [PromoteAllScalars = true]),
				  #"Zmieniono typ kolumny" = Table.TransformColumnTypes(#"Nagłówki o podwyższonym poziomie", {{"page_id", Int64.Type}, {"year", Int64.Type}, {"month", Int64.Type}, {"rank", Int64.Type}, {"title", type text}, {"views", Int64.Type}}, "pl")
				in
				  #"Zmieniono typ kolumny"

